SELECT count(*) from `listingdata`;

SHOW WARNINGS;

SELECT * from `listingdata`;

CREATE TABLE `nyc_airbnb_data`.`listingdata` (
    listing_id INT,
    listing_type VARCHAR(100),
    room_type VARCHAR(100),
    photos_count VARCHAR(10),
    host_id INT,
    superhost VARCHAR(10),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    guests VARCHAR(10),
    bedrooms VARCHAR(10),
    beds VARCHAR(10),
    baths VARCHAR(10),
    registration VARCHAR(10),
    instant_book VARCHAR(10),
    professional_management VARCHAR(10),
    min_nights INT,
    cancellation_policy VARCHAR(50),
    checkin_time VARCHAR(20),
    checkout_time VARCHAR(20),
    guest_favorite VARCHAR(10),
    exact_location VARCHAR(10),
    currency VARCHAR(10),
    cleaning_fee VARCHAR(20),
    extra_guest_fee VARCHAR(20),
    single_fee_structure VARCHAR(10),
    num_reviews INT,
    rating_overall VARCHAR(20),
rating_accuracy VARCHAR(20),
rating_checkin VARCHAR(20),
rating_cleanliness VARCHAR(20),
rating_communication VARCHAR(20),
rating_location VARCHAR(20),
rating_value VARCHAR(20),
    ttm_revenue DECIMAL(12,2),
    ttm_revenue_native DECIMAL(12,2),
    ttm_avg_rate DECIMAL(10,2),
    ttm_avg_rate_native DECIMAL(10,2),
    ttm_occupancy DECIMAL(5,3),
    ttm_adjusted_occupancy DECIMAL(5,3),
    ttm_revpar DECIMAL(10,2),
    ttm_revpar_native DECIMAL(10,2),
    ttm_adjusted_revpar DECIMAL(10,2),
    ttm_adjusted_revpar_native DECIMAL(10,2),
    ttm_avg_min_nights DECIMAL(6,2),
    ttm_avg_length_of_stay DECIMAL(6,2),
    ttm_reserved_days INT,
    ttm_blocked_days INT,
    ttm_available_days INT,
    ttm_total_days INT,
    l90d_revenue DECIMAL(12,2),
    l90d_revenue_native DECIMAL(12,2),
    l90d_avg_rate DECIMAL(10,2),
    l90d_avg_rate_native DECIMAL(10,2),
    l90d_occupancy DECIMAL(5,3),
    l90d_adjusted_occupancy DECIMAL(5,3),
    l90d_revpar DECIMAL(10,2),
    l90d_revpar_native DECIMAL(10,2),
    l90d_adjusted_revpar DECIMAL(10,2),
    l90d_adjusted_revpar_native DECIMAL(10,2),
    l90d_avg_min_nights DECIMAL(6,2),
    l90d_avg_length_of_stay DECIMAL(6,2),
    l90d_reserved_days INT,
    l90d_blocked_days INT,
    l90d_available_days INT,
    l90d_total_days INT
);
